### PR TITLE
Include time that PUP-1072 was discussed

### PR DESCRIPTION
**Pull request by pjfoley**

### CODE REVIEW

**Comment by kylog** [comment]
@pjfoley I'm fine with not using PR workflow for the meeting notes. But I can't remember if someone gave you push rights or not? Meanwhile, merging ....

**Comment by nibalizer** [comment]
Please don't create PRs for this. you can push this change directly in.

**Comment by pjfoley** [comment]
Hi Guys,

Sorry I have not had write access to another organisation's repo before.
For some reason I thought it would just work using the github web interface
edit capability (I am positive I have done this before with my own repo's
and it did not create a PR).

I will use git to pull it down and update it if necessary in future.

Sorry for the trouble.

Peter

**Comment by kylog** [comment]
No worries @pjfoley. Thanks for contributing!

**Pull request merged**
